#!/usr/bin/env node
/**
 * EvDb Stream Factory Code Generator
 *
 * Scans a *Events/ directory, extracts `payloadType` literals from POCO event types,
 * and regenerates the sibling *StreamFactory.ts file.
 *
 * Usage:
 *   tsx packages/core/src/codegen/generateStreamFactory.ts <events-dir> <stream-type>
 *
 * Example:
 *   tsx packages/core/src/codegen/generateStreamFactory.ts \
 *     apps/sample-app/src/eventstore/FundsStream/FundsEvents \
 *     funds-stream
 *
 * The generated factory file is written next to the events directory.
 */

import * as fs from "node:fs";
import * as path from "node:path";

interface EventInfo {
  typeName: string;
  payloadType: string;
  importPath: string;
}

/**
 * Extracts the exported type/class name and its `payloadType` literal from a TS source file.
 * Handles both:
 *   export type Foo = ... & { readonly payloadType: "Foo"; ... }
 *   export class Foo implements ... { readonly payloadType = "Foo"; }
 */
function extractEventInfo(filePath: string): EventInfo | null {
  const source = fs.readFileSync(filePath, "utf-8");

  // Match: payloadType: "SomeLiteral"  (type alias)
  // or:    payloadType = "SomeLiteral"  (class property)
  const payloadTypeMatch = source.match(/payloadType[:\s=]+["']([^"']+)["']/);
  if (!payloadTypeMatch) return null;

  const payloadType = payloadTypeMatch[1];

  // Match exported type or class name
  const exportMatch = source.match(/export\s+(?:type|class)\s+(\w+)/);
  if (!exportMatch) return null;

  const typeName = exportMatch[1];

  return { typeName, payloadType, importPath: filePath };
}

function generateFactory(eventsDir: string, streamType: string): void {
  const absoluteEventsDir = path.resolve(eventsDir);

  if (!fs.existsSync(absoluteEventsDir)) {
    throw new Error(`Events directory not found: ${absoluteEventsDir}`);
  }

  const eventFiles = fs
    .readdirSync(absoluteEventsDir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
    .map((f) => path.join(absoluteEventsDir, f));

  const events: EventInfo[] = [];
  for (const file of eventFiles) {
    const info = extractEventInfo(file);
    if (info) events.push(info);
  }

  if (events.length === 0) {
    throw new Error(`No event types found in: ${absoluteEventsDir}`);
  }

  // Determine output path: sibling of eventsDir named <ParentStream>Factory.ts
  const parentDir = path.dirname(absoluteEventsDir);
  const eventsDirName = path.basename(absoluteEventsDir); // e.g. "FundsEvents"
  const streamName = eventsDirName.replace(/Events$/, ""); // e.g. "Funds"
  const outputPath = path.join(parentDir, `${streamName}StreamFactory.ts`);

  // Relative import paths from the factory file to each event file
  const relativeEventsDir = `./${eventsDirName}`;

  const imports = events
    .map((e) => `import type { ${e.typeName} } from "${relativeEventsDir}/${e.typeName}.js";`)
    .join("\n");

  // Zero-arg withEvent calls — type inference only, Proxy handles runtime dispatch
  const withEventCalls = events.map((e) => `  .withEvent<${e.typeName}>()`).join("\n");

  const streamVarName = `${streamName}StreamFactory`;

  const output = `// @generated by evdb-codegen — do not edit manually
// Source: ${path.relative(parentDir, absoluteEventsDir)}
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
${imports}

const ${streamVarName} = new StreamFactoryBuilder("${streamType}")
${withEventCalls}
  .build();

export default ${streamVarName};

export type ${streamName}StreamType = typeof ${streamVarName}.StreamType;
`;

  fs.writeFileSync(outputPath, output, "utf-8");
  console.log(`Generated: ${outputPath}`);
  events.forEach((e) => console.log(`  - ${e.typeName} (payloadType: "${e.payloadType}")`));
}

// CLI entry point
const [eventsDir, streamType] = process.argv.slice(2);

if (!eventsDir || !streamType) {
  console.error(
    "Usage: tsx generateStreamFactory.ts <events-dir> <stream-type>\n" +
      "Example: tsx generateStreamFactory.ts apps/sample-app/src/eventstore/FundsStream/FundsEvents funds-stream",
  );
  process.exit(1);
}

generateFactory(eventsDir, streamType);
