// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import { FundsDenied } from "./FundsEvents/FundsDenied.js";
import { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";

const FundsEventsAndViewsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEventType(FundsCaptured)
  .withEventType(FundsDenied)
  .withEventType(FundsDeposited)
  .withEventType(FundsRefunded)
  .withEventType(FundsWithdrawal)
  .withView("balance", 0, {
    FundsDeposited: (state, event) => state + event.amount,
    FundsRefunded: (state, event) => state - event.amount,
    FundsCaptured: (state, event) => state - event.amount,
    FundsWithdrawal: (state, event) => state - event.amount,
  })
  .build();

export default FundsEventsAndViewsStreamFactory;

export type FundsEventsAndViewsStreamType = typeof FundsEventsAndViewsStreamFactory.StreamType;
