// @generated by evdb-codegen — do not edit manually
// Source: FundsStreamSpec.ts
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";

export const FundsStreamFactory = (streamType: string) =>
  new StreamFactoryBuilder(streamType)
    .withEvent<FundsCaptured>("FundsCaptured")
    .withEvent<FundsDenied>("FundsDenied")
    .withEvent<FundsDeposited>("FundsDeposited")
    .withEvent<FundsRefunded>("FundsRefunded")
    .withEvent<FundsWithdrawal>("FundsWithdrawal");

export type FundsStreamType = ReturnType<typeof FundsStreamFactory>;
