import { WithEvent } from "@eventualize/core/factories/WithEvent";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";

@WithEvent<FundsCaptured>()
@WithEvent<FundsDenied>()
@WithEvent<FundsDeposited>()
@WithEvent<FundsRefunded>()
@WithEvent<FundsWithdrawal>()
export class FundsStreamSpec { }

// TODO: move the generated file under generated/ and keep the relative path the same as the source file
// @generated by evdb-codegen — do not edit manually
// Source: FundsStreamSpec.ts

// generate the events as a union type for easier use in reducers and other places where we want to handle multiple event types
// export type FundsStreamEvent =
//   | FundsCaptured
//   | FundsDenied
//   | FundsDeposited
//   | FundsRefunded
//   | FundsWithdrawal;


