// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";

const FundsPureEventsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEvent("FundsCaptured").asType<FundsCaptured>()
  .withEvent("FundsDenied").asType<FundsDenied>()
  .withEvent("FundsDeposited").asType<FundsDeposited>()
  .withEvent("FundsRefunded").asType<FundsRefunded>()
  .withEvent("FundsWithdrawal").asType<FundsWithdrawal>()
  .build();

export default FundsPureEventsStreamFactory;

export type FundsPureEventsStreamType = typeof FundsPureEventsStreamFactory.StreamType;
