// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import EvDbMessage from "@eventualize/types/messages/EvDbMessage";
const FundsEventsAndViewsStreamFactory = new StreamFactoryBuilder("funds-stream")
    .withEvent("FundsCaptured").asType()
    .withEvent("FundsDenied").asType()
    .withEvent("FundsDeposited").asType()
    .withEvent("FundsRefunded").asType()
    .withEvent("FundsWithdrawal").asType()
    .withView("balance", 0, {
    FundsDeposited: (state, event) => state + event.amount,
    FundsRefunded: (state, event) => state - event.amount,
    FundsCaptured: (state, event) => state - event.amount,
    FundsWithdrawal: (state, event) => state - event.amount,
})
    .withView("count", new Map(), {
    FundsDeposited: (state) => state.set("deposited", (state.get("deposited") ?? 0) + 1),
    FundsRefunded: (state) => state.set("refunded", (state.get("refunded") ?? 0) + 1),
    FundsCaptured: (state) => state.set("captured", (state.get("captured") ?? 0) + 1),
    FundsWithdrawal: (state) => state.set("withdrawal", (state.get("withdrawal") ?? 0) + 1),
})
    .withMessages("FundsCaptured", (payload, views, metadata) => [
    EvDbMessage.createFromMetadata(metadata, "Funds Captured with Balance Notification", {
        amountCaptured: payload.amount,
        balanceAfterCapture: views.balance,
    }),
])
    .build();
export default FundsEventsAndViewsStreamFactory;
//# sourceMappingURL=FundsEventsAndViewsStreamFactory.js.map