// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";
import { FundsEventNames } from "./FundsEventNames.js";

const FundsFullEventsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEvent<FundsCaptured>(FundsEventNames.FundsCaptured)
  .withEvent<FundsDenied>(FundsEventNames.FundsDenied)
  .withEvent<FundsDeposited>(FundsEventNames.FundsDeposited)
  .withEvent<FundsRefunded>(FundsEventNames.FundsRefunded)
  .withEvent<FundsWithdrawal>(FundsEventNames.FundsWithdrawal)
  .withMessages()
  .build();

export default FundsFullEventsStreamFactory;

export type FundsFullEventsStreamType = typeof FundsFullEventsStreamFactory.StreamType;
