// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";

const FundsEventsAndViewsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEventType("FundsCaptured").as<FundsCaptured>()
  .withEventType("FundsDenied").as<FundsDenied>()
  .withEventType("FundsDeposited").as<FundsDeposited>()
  .withEventType("FundsRefunded").as<FundsRefunded>()
  .withEventType("FundsWithdrawal").as<FundsWithdrawal>()
  .withView("balance", 0, {
    FundsDeposited: (state, event) => state + event.amount,
    FundsRefunded: (state, event) => state - event.amount,
    FundsCaptured: (state, event) => state - event.amount,
    FundsWithdrawal: (state, event) => state - event.amount,
  })
  .build();

export default FundsEventsAndViewsStreamFactory;

export type FundsEventsAndViewsStreamType = typeof FundsEventsAndViewsStreamFactory.StreamType;