// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder, fromEvents } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";
import { FundsEventNames } from "./FundsEventNames.js";
import type IEvDbEventMetadata from "@eventualize/types/events/IEvDbEventMetadata";

type AllEventTypes = FundsCaptured | FundsDenied | FundsDeposited | FundsRefunded | FundsWithdrawal;

const FundsFullEventsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEvent<FundsCaptured>(FundsEventNames.FundsCaptured)
  .withEvent<FundsDenied>(FundsEventNames.FundsDenied)
  .withEvent<FundsDeposited>(FundsEventNames.FundsDeposited)
  .withEvent<FundsRefunded>(FundsEventNames.FundsRefunded)
  .withEvent<FundsWithdrawal>(FundsEventNames.FundsWithdrawal)
  .withViews()
  .addView("balance", 0, {
    [FundsEventNames.FundsDeposited]: (oldState: number, event: FundsDeposited) =>
      oldState + event.amount,
    [FundsEventNames.FundsWithdrawal]: (oldState: number, event: FundsWithdrawal) =>
      oldState - event.amount,
    [FundsEventNames.FundsCaptured]: (oldState: number, event: FundsCaptured) =>
      oldState - event.amount,
    [FundsEventNames.FundsRefunded]: (oldState: number, event: FundsRefunded) =>
      oldState + event.amount,
  })
  .addView(
    "max-deposit",
    0,
    fromEvents((b) =>
      b.fromFundsDeposited((oldState: number, event: FundsDeposited) =>
        oldState > event.amount ? oldState : event.amount,
      ),
    ),
  )
  .addView(
    "last-activity",
    [],
    (_oldState: string[], event: AllEventTypes, meta: IEvDbEventMetadata) =>
      _oldState.length < 10
        ? [..._oldState, meta.eventType]
        : [..._oldState.slice(1), meta.eventType],
  )
  .withMessages()
  .addFundsDeposited("Funds Deposited Notification", (payload, views) => ({
    amount: payload.amount,
    PointsSum: views.balance,
  }))
  .build();

export default FundsFullEventsStreamFactory;

export type FundsFullEventsStreamType = typeof FundsFullEventsStreamFactory.StreamType;
