// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder, evt } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "./FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "./FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "./FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "./FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "./FundsEvents/FundsWithdrawal.js";
import { FundsEventNames } from "./FundsEventNames.js";

const FundsPureEventsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEventType(evt<FundsCaptured, FundsEventNames.FundsCaptured>(FundsEventNames.FundsCaptured))
  .withEventType(evt<FundsDenied, FundsEventNames.FundsDenied>(FundsEventNames.FundsDenied))
  .withEventType(
    evt<FundsDeposited, FundsEventNames.FundsDeposited>(FundsEventNames.FundsDeposited),
  )
  .withEventType(evt<FundsRefunded, FundsEventNames.FundsRefunded>(FundsEventNames.FundsRefunded))
  .withEventType(
    evt<FundsWithdrawal, FundsEventNames.FundsWithdrawal>(FundsEventNames.FundsWithdrawal),
  )
  .build();

export default FundsPureEventsStreamFactory;

export type FundsPureEventsStreamType = typeof FundsPureEventsStreamFactory.StreamType;
