// @generated by evdb-codegen — do not edit manually
// Source: FundsEvents
import { StreamFactoryBuilder } from "@eventualize/core/factories/StreamFactoryBuilder";
import type { FundsCaptured } from "../FundsEvents/FundsCaptured.js";
import type { FundsDenied } from "../FundsEvents/FundsDenied.js";
import type { FundsDeposited } from "../FundsEvents/FundsDeposited.js";
import type { FundsRefunded } from "../FundsEvents/FundsRefunded.js";
import type { FundsWithdrawal } from "../FundsEvents/FundsWithdrawal.js";
import { FundsEventNames } from "../FundsEventNames.js";
import type IEvDbEventMetadata from "@eventualize/types/events/IEvDbEventMetadata";

type AllEventTypes = FundsCaptured | FundsDenied | FundsDeposited | FundsRefunded | FundsWithdrawal;

const FundsFullEventsStreamFactory = new StreamFactoryBuilder("funds-stream")
  .withEvent<FundsCaptured>(FundsEventNames.FundsCaptured)
  .withEvent<FundsDenied>(FundsEventNames.FundsDenied)
  .withEvent<FundsDeposited>(FundsEventNames.FundsDeposited)
  .withEvent<FundsRefunded>(FundsEventNames.FundsRefunded)
  .withEvent<FundsWithdrawal>(FundsEventNames.FundsWithdrawal)
  .withViews()
  // TODO: illegal signature, "X" is not a valid event type
  .addViewPattern("balance", 0, {
    ["X"]: (oldState: number, event: FundsDeposited) => oldState + event.amount,
  })
  .addViewBuilder("max-deposit", 0, (b) =>
    b
      .fromFundsDeposited((oldState: number, event: FundsDeposited) =>
        oldState > event.amount ? oldState : event.amount,
      )
      .fromFundsWithdrawal((oldState: number, event: FundsWithdrawal) =>
        oldState > event.amount ? oldState : event.amount,
      )
      // TODO: illegal signature, "fromIllegal" is not a valid event type
      .fromIllegal((oldState: number, event: FundsWithdrawal) =>
        oldState > event.amount ? oldState : event.amount,
      ),
  )
  .addView(
    "last-activity",
    [],
    (_oldState: string[], event: AllEventTypes, meta: IEvDbEventMetadata) =>
      _oldState.length < 10
        ? [..._oldState, meta.eventType]
        : [..._oldState.slice(1), meta.eventType],
  )
  .addView(
    "last-activity-fixed-event",
    [],
    (_oldState: string[], event, meta: IEvDbEventMetadata) =>
      _oldState.length < 10
        ? [..._oldState, meta.eventType]
        : [..._oldState.slice(1), meta.eventType],
  )
  // NOT TODO: do catch the illegal signature, event type is not in the stream's event types
  // .addView(
  //   "last-activity",
  //   [],
  //   (_oldState: string[], event: IEvDbEventType, meta: IEvDbEventMetadata) =>
  //     _oldState.length < 10
  //       ? [..._oldState, meta.eventType]
  //       : [..._oldState.slice(1), meta.eventType],
  // )
  .withMessages()
  // TODO: illegal signature, "addFundsRefunded" should allow FundsRefunded event type, not FundsDeposited
  .addFundsRefunded("Funds Refunded Notification", (payload: FundsDeposited, views) => ({
    amount: payload.amount,
    PointsSum: views.balance,
  }))
  // TODO: illegal signature, "addFundsNotExists" is not a valid event type for this stream
  .addFundsNotExists("Funds Not Exists Notification", (payload, views) => ({
    amount: payload.amount,
    PointsSum: views.balance,
  }))

  .build();

export default FundsFullEventsStreamFactory;

export type FundsFullEventsStreamType = typeof FundsFullEventsStreamFactory.StreamType;
